language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "nexsin" # the key of the org you chose at step #3
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "$DOCKER_USERNAME"
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      #- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag unige/api-gateway nexsin/api-gateway:latest
      - docker tag unige/regulatory-service nexsin/regulatory-service:latest
      - docker tag unige/valuation-service nexsin/valuation-service:latest
      - docker tag unige/instrument-service nexsin/instrument-service:latest
      - docker tag unige/counterparty-service nexsin/counterparty-service:latest     
      - docker push nexsin/api-gateway:latest
      - docker push nexsin/regulatory-service:latest
      - docker push nexsin/valuation-service:latest
      - docker push nexsin/instrument-service:latest
      - docker push nexsin/counterparty-service:latest
#      - mvn sonar:sonar -Dsonar.projectKey=rolandogdp_microservices -Dsonar.organization=rolandogdp -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
#      - mvn sonar:sonar -Dsonar.projectKey=rolandogdp_microservices
#      - mvn sonar:sonar -Dsonar.projectKey=rolandogdp_microservices -Dsonar.organization=rolandogdp -Dsonar.host.url=https://sonarcloud.io 

      - mvn sonar:sonar -Dsonar.projectKey=samako96_microservices -Dsonar.organization=samako96 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2a08e0c77c224f06d27c7a9dbd34edd78467cb8d     
 #     - sonar-scanner
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      
      - docker tag unige/web-ui nexsin/web-ui:latest      
      - docker push nexsin/web-ui:latest
